services:
  # docker compose up mysql -d
  mysql:
    image: 'mysql:latest'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=db0
      - MYSQL_USER=whoami
      - MYSQL_PASSWORD=pass
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
  # docker compose down mysql -v

  # docker-compose up -d redis_service
  redis_service:
    image: redis:latest
    container_name: redis_container
    hostname: redis_host
    ports:
      - "6379:6379"
    restart: always
  # docker-compose down redis_service -v
